### ISSUE TITLE
How to generate similarity mat for custom data? 

### ISSUE THREAD

**Issue by tianchen-ns** [youngkyunJang/GPQ#2]
Nice work and Thanks!
Meanwhile the downloaded mat for CIFAR10 can't be loaded correctly.

**Comment by youngkyunJang** [comment]
Hello thanks for your compliment!
We have precomputed and uploaded cifar10 similarity matrix on "data".

If you want to build your own similarity matrix, you can follow this code and save the result.

    def label_Sim_Generate(traingnd, testgnd):

        numtrain = traingnd.shape[0]
        numtest = testgnd.shape[0]

        label_Sim = np.zeros((numtest, numtrain))

        for i in range(numtest):
            for j in range(numtrain):
                if np.dot(traingnd[j],testgnd[i])!=0:
                    label_Sim[i,j] = 1
             if i%100 == 0:
                print("%d-th processing"%(i))

        return label_Sim

Good luck!

**Comment by youngkyunJang** [comment]
This issue is solved and I closed.
