### ISSUE TITLE
How to generate NUS-Wide dataset ?

### ISSUE THREAD

**Issue by chengshuai1992** [youngkyunJang/GPQ#4]
Hi,
There are a total of 27000 images in the NUS dataset. I chose the 21 most popular classes, with a total of 195834 images. But, the experimental results are much worse than those in the paper. Can you provide the name list and label of train and test image database.

**Comment by youngkyunJang** [comment]
Hello.

I followed the works done in here, https://github.com/whksmo/HashNet.
You can find the lists of train/test sets.

Acutullay, I also had made label similarity matrix for NUS-WIDE 21 set, but it's too huge to upload so I didn't upload :(

You can obtain it following issue #2 .

**Comment by youngkyunJang** [comment]
This issue is solved and I closed.
