### ISSUE TITLE
The details about Nuswide 

### ISSUE THREAD

**Issue by lpdone** [youngkyunJang/GPQ#6]
1.hello, what are the specific mean and variance in nuswide?
 

def color_preprocessing(x_):
    #Normalize with mean and std of source data
    x_ = x_.astype('float32')
    x_[:, :, :, 0] = (x_[:, :, :, 0] - 125.642) / 63.01
    x_[:, :, :, 1] = (x_[:, :, :, 1] - 123.738) / 62.157
    x_[:, :, :, 2] = (x_[:, :, :, 2] - 114.46) / 66.94
    return x_

2. In nuswide, can specific training lists and test lists be provided?

Good work and thanks！

**Comment by youngkyunJang** [comment]
Hello

Since we utilize ImageNet pretrained weights, you can use the same mean and variance.

and we organize and upload the list as you request, following <a href="https://github.com/thuml/HashNet">HashNet</a>.

Good luck!

**Comment by lpdone** [comment]
Thank you！
