### ISSUE TITLE
How to use the cnn-f network to replace the vgg network ?

### ISSUE THREAD

**Issue by chengshuai1992** [youngkyunJang/GPQ#7]
Unfortunately, my server cannot run VGG network because there are too many network parameters. So I want to use CNN-F (Alexnet) instead of VGG. Two Global_Average_Pooling methods are used in the VGG network and the full connection layer is removed. Can you tell me how to modify in CNN-F(AlexNet) network?
thanks!

**Comment by youngkyunJang** [comment]
Hello,

Since CNN-F contains more parameters to be trained (a lot of fully connected weights),

it will be better to use our model for low  computing environments.

If the model is too huge for training, you can simply modify the batch size to fit in.

Good luck!
