### ISSUE TITLE
Wrong cosine similarity in N_PQ_loss?

### ISSUE THREAD

**Issue by drcege** [youngkyunJang/GPQ#8]
It is said, "S_b in the N-PQ loss (i.e., Equation 2 in the paper) denotes a cosine similarity between b-th feature vector and every quantized vector". According to the code, this is implemented by matrix multiplication:
https://github.com/youngkyunJang/GPQ/blob/80963838a3e6d11c6bdae15908ce544d8424a0eb/utils/Functions.py#L99
However, `embeddings_x` (i.e., feature_S) is intra-normalized, but `embeddings_q` (i.e., descriptor_S) is **NOT**. (This can be verified by printing the sub-vector norm.)

So, this is actually not the cosine similarity, but just an ordinary inner product. The product does not reflect a similarity measure in the conventional sense, and may affect the results.

**Comment by youngkyunJang** [comment]
Thanks to find out our mistake

We will fix it as soon as possible!

**Comment by youngkyunJang** [comment]
We fixed it so closed the issue

**Comment by drcege** [comment]
In fact, there are still some problematic implementations. 

For example, in Soft_Assignment, the passed`net.Z` and `Z` are not intra-normalized.
https://github.com/youngkyunJang/GPQ/blob/1621e33bfa335bf20377cfcd420d709eb805a595/utils/Functions.py#L70

Also in `Indexing` when performing retrieval.
https://github.com/youngkyunJang/GPQ/blob/1621e33bfa335bf20377cfcd420d709eb805a595/utils/RetrievalTest.py#L42

**Comment by youngkyunJang** [comment]
Oh I see, Thanks for your advice!
